name: Auto Update Index HTML

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: #'00 13 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Checkout Main Branch
        run: |
          git checkout main
          git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests google-generativeai feedparser

      - name: Run main.py
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TRANSLATE_API_KEY: ${{ secrets.TRANSLATE_API_KEY }}
          PAPER_API_KEY: ${{ secrets.PAPER_API_KEY }}
          SPRINGER_API_KEY: ${{ secrets.SPRINGER_API_KEY }}
        run: python main.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add index.html science_data.db
          
          if ! git diff --quiet || ! git diff --staged --quiet; then
            git commit -m "Update data [skip ci]"
            
            git pull --rebase -Xtheirs origin main
            
            git push origin main
          else
            echo "No changes to commit"
          fi
